name: Checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: warp-ubuntu-latest-x64-32x
    env:
      # Set features for the Makefile
      FEATURES: ${{ matrix.features }}
    strategy:
      matrix:
        toolchain:
          - nightly
        features:
          - ""

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/dtolnay/rust-toolchain
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "rustfmt,clippy"

      # https://github.com/swatinem/rust-cache
      - name: Run Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        if: ${{ !env.ACT }}
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          cache-on-failure: true

      # https://github.com/Mozilla-Actions/sccache-action
      - name: Run sccache-action
        if: ${{ !env.ACT }}
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Set sccache env vars
        if: ${{ !env.ACT }}
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly

      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev clang libclang-dev llvm build-essential pkg-config libtss2-dev

      - name: Compile tester
        run: make tester

      - name: Compile op-rbuilder
        run: cargo build -p op-rbuilder --bin op-rbuilder

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          TESTS_TEMP_DIR: ${{ github.workspace }}
